### ISSUE TITLE
App crash on when search something (enter any word which is not find on any website) 

### ISSUE THREAD

**Issue by imalixch** [priyanktejani/fluid-torrent-search-engine#2]
Here is the Log:
2022-07-18 16:25:02.070 7424-7581/com.fluidtorrentz.torrentsearch E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
    Process: com.fluidtorrentz.torrentsearch, PID: 7424
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:399)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.jsoup.nodes.Element.remove()' on a null object reference
        at com.fluidtorrentz.torrentsearch.fragments.PirateBayFragment$loadSearchResult.doInBackground(PirateBayFragment.java:151)
        at com.fluidtorrentz.torrentsearch.fragments.PirateBayFragment$loadSearchResult.doInBackground(PirateBayFragment.java:137)

Here is the Line on crash: 

tBody.select("tr").last().remove();

**Comment by muzamilrafiq798** [comment]
Hi, can you upload apk?
